platform :ios, '7.0'

pod 'AFNetworking', :podspec => 'https://raw.github.com/AFNetworking/AFNetworking/master/AFNetworking.podspec'
pod 'MJStarRating', :podspec => 'MJStarRating.podspec'
pod 'GMGridView'
pod 'OBGradientView', :podspec => 'OBGradientView.podspec'
pod 'BlockAlertsAnd-ActionSheets', :podspec => 'BlockAlertsAnd-ActionSheets.podspec'
pod 'KSReachability', :podspec => 'KSReachability.podspec'
pod 'UIResponder+KeyboardCache'
pod 'UISS'
pod 'HockeySDK'
pod 'Mantle'

#pod 'TestFlightSDK'
#pod 'iOS-Hierarchy-Viewer'
#pod 'PonyDebugger'
#pod 'MBProgressHUD'