platform :ios, '7.0'

pod 'AFNetworking', :podspec => 'https://raw.github.com/AFNetworking/AFNetworking/master/AFNetworking.podspec'
pod 'MJStarRating', :podspec => 'MJStarRating.podspec'
pod 'GMGridView'
pod 'KSReachability', :podspec => 'KSReachability.podspec'
pod 'UIResponder+KeyboardCache'
pod 'HockeySDK', :podspec => 'https://raw.github.com/bitstadium/HockeySDK-iOS/develop/HockeySDK.podspec'
pod 'Mantle'
pod 'BlocksKit'
pod "Reveal-iOS-SDK"
pod 'iOS-blur'

#pod 'TestFlightSDK'
#pod 'iOS-Hierarchy-Viewer'
#pod 'PonyDebugger'
#pod 'MBProgressHUD'
#pod 'UISS'
#pod 'BlockAlertsAnd-ActionSheets', :podspec => 'BlockAlertsAnd-ActionSheets.podspec'
#pod 'OBGradientView', :podspec => 'OBGradientView.podspec'